language: php

php:
  - 7.2

sudo: false

before_install:
  - echo -e "{\"http-basic\":{\"nova.laravel.com\":{\"username\":$CI_USER_NAME,\"password\":$CI_USER_PASSWORD}}}" > ~/.composer/auth.json
  - phpenv config-rm xdebug.ini
  - printf "\n" | pecl install -f redis

install: travis_retry composer install --no-interaction --prefer-dist --no-suggest

script: composer test
